# Generated by Django 4.1.2 on 2022-10-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[(1, 'À faire'), (2, 'En cours'), (3, 'Finie')], default=1, max_length=100)),
                ('limit_date', models.DateField()),
            ],
        ),
    ]
