# Generated by Django 4.1.2 on 2022-10-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'À faire'), (2, 'En cours'), (3, 'Finie')], default=1),
        ),
    ]
